In [34]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\navee\miniconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\navee\miniconda3\lib\site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\navee\miniconda3\lib\site-packages (from pandas) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\navee\miniconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\navee\miniconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\navee\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [52]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\navee\miniconda3\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\navee\miniconda3\lib\site-packages (from scikit-learn) (2.0.0)
Requirement already satisfied: scipy>=1.6.0 in c:\users\navee\miniconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\navee\miniconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\navee\miniconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [53]:
pip show scikit-learn

Name: scikit-learn
Version: 1.5.1
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author:
Author-email:
License: new BSD
Location: c:\users\navee\miniconda3\lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [35]:
!ls ../data

data_description.txt
sample_submission.csv
test.csv
train.csv

In [36]:
import pandas as pd

DATA_FILENAME = '../data/train.csv'

# Read data

- Read data

In [37]:
df_raw = pd.read_csv(DATA_FILENAME)

- Show head of data (first 5 rows)

In [38]:
df_raw.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [39]:
df_raw.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [40]:
df_raw.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

- check how many rows you have in the data

In [41]:
df_raw.shape

(1460, 81)

- Filter data

In [71]:
label_col = 'SalePrice'
useful_features = ['Foundation', 'KitchenQual', 'ExterQual','TotRmsAbvGrd', 'WoodDeckSF', 'YrSold', '1stFlrSF']

In [72]:
df = df_raw[useful_features + [label_col]]
df.head()

,Foundation,KitchenQual,ExterQual,TotRmsAbvGrd,WoodDeckSF,YrSold,1stFlrSF,SalePrice
0,PConc,Gd,Gd,8,0,2008,856,208500
1,CBlock,TA,TA,6,298,2007,1262,181500
2,PConc,Gd,Gd,6,0,2008,920,223500
3,BrkTil,Gd,TA,7,0,2006,961,140000
4,PConc,Gd,Gd,9,192,2008,1145,250000

In [73]:
df.shape

(1460, 8)

# Preprocess data

In [74]:
continuous_features = ['TotRmsAbvGrd', 'YrSold']
discrete_features = ['Foundation', 'KitchenQual']
features_to_one_hot_encode = ['Foundation']
features_to_oridinal_encode = ['KitchenQual','ExterQual']

- check the values and the count of a given feature

In [75]:
df['Foundation'].value_counts()

Foundation
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: count, dtype: int64

In [76]:
df['TotRmsAbvGrd'].value_counts()

TotRmsAbvGrd
6     402
7     329
5     275
8     187
4      97
9      75
10     47
11     18
3      17
12     11
2       1
14      1
Name: count, dtype: int64

In [77]:
df['KitchenQual'].value_counts()

KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64

In [78]:
df['ExterQual'].value_counts()

ExterQual
TA    906
Gd    488
Ex     52
Fa     14
Name: count, dtype: int64

## encoding

In [79]:
df_one_hot_code = pd.get_dummies(df[features_to_one_hot_encode])
df_one_hot_code.head()

,Foundation_BrkTil,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood
0,False,False,True,False,False,False
1,False,True,False,False,False,False
2,False,False,True,False,False,False
3,True,False,False,False,False,False
4,False,False,True,False,False,False

## TODO
- categorize the rest of features
- scale continuous features (df_scaled)
- ordinal encode categorical features (quality, etc) (df_ordinal_encoded)
- Concat the 3 dataframes in a single one (df_one_hot_code, df_ordinal_encoded, df_scaled)

In [87]:
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder

In [88]:
ordinal_features = ['KitchenQual','ExterQual']
ordinal_categories = [
    ['Fa', 'TA', 'Gd', 'Ex'], 
    ['Fa', 'TA', 'Gd', 'Ex']   
]
ordinal_encoder = OrdinalEncoder(categories=ordinal_categories)
df_ordinal_encoded = pd.DataFrame(ordinal_encoder.fit_transform(df[ordinal_features]), columns=ordinal_features)

In [89]:
scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df[continuous_features]), columns=continuous_features)

In [93]:
df_final = pd.concat([df_one_hot_code, df_ordinal_encoded, df_scaled, df['SalePrice']], axis=1)

In [94]:
df_final.head(20)

,Foundation_BrkTil,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood,KitchenQual,ExterQual,TotRmsAbvGrd,YrSold,SalePrice
0,False,False,True,False,False,False,2.0,2.0,0.912210,0.138777,208500
1,False,True,False,False,False,False,1.0,1.0,-0.318683,-0.614439,181500
2,False,False,True,False,False,False,2.0,2.0,-0.318683,0.138777,223500
3,True,False,False,False,False,False,2.0,1.0,0.296763,-1.367655,140000
4,False,False,True,False,False,False,2.0,2.0,1.527656,0.138777,250000
5,False,False,False,False,False,True,1.0,1.0,-0.934130,0.891994,143000
6,False,False,True,False,False,False,2.0,2.0,0.296763,-0.614439,307000
7,False,True,False,False,False,False,1.0,1.0,0.296763,0.891994,200000
8,True,False,False,False,False,False,1.0,1.0,0.912210,0.138777,129900
9,True,False,False,False,False,False,1.0,1.0,-0.934130,0.138777,118000
10,False,True,False,False,False,False,1.0,1.0,-0.934130,0.138777,129500
11,False,False,True,False,False,False,3.0,3.0,2.758549,-1.367655,345000
12,False,True,False,False,False,False,1.0,1.0,-1.549576,0.138777,144000
13,False,False,True,False,False,False,2.0,2.0,0.296763,-0.614439,279500
14,False,True,False,False,False,False,1.0,1.0,-0.934130,0.138777,157000
15,True,False,False,False,False,False,1.0,1.0,-0.934130,-0.614439,132000
16,False,True,False,False,False,False,1.0,1.0,-0.934130,1.645210,149000
17,False,False,False,True,False,False,1.0,1.0,-0.318683,-1.367655,90000
18,False,False,True,False,False,False,2.0,1.0,-0.318683,0.138777,159000
19,False,True,False,False,False,False,1.0,1.0,-0.318683,0.891994,139000

# Training

- Create X and y

In [95]:
X, y = df_final.drop(columns=[label_col]), df_final[label_col]

- Split data in X_train, y_train, X_test, y_test https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

In [96]:
# TODO
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=30)

- Instantiate a LinearRegressor https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

In [97]:
# TODO
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
model = LinearRegression()

- Train the model (model.fit ...)

In [98]:
# TODO
model.fit(X_train, y_train)

LinearRegression()

# Evaluation

- make predictions (`y_pred = model.predict(X_test)`)

In [102]:
y_pred = model.predict(X_test)

- compute performance using https://scikit-learn.org/stable/modules/generated/sklearn.metrics.root_mean_squared_error.html#sklearn.metrics.root_mean_squared_error

In [103]:
import numpy as np
from sklearn.metrics import mean_squared_log_error

def compute_rmsle(y_test: np.ndarray, y_pred: np.ndarray, precision: int = 2) -> float:
    rmsle = np.sqrt(mean_squared_log_error(y_test, y_pred))
    return round(rmsle, precision)

In [104]:
rmsle = compute_rmsle(y_test,y_pred)
print(f'Root Mean Squared Logarithmic Error (RMSLE): {rmsle}')

Root Mean Squared Logarithmic Error (RMSLE): 0.26